//------------------------------------------------------------------------------
// This is auto-generated code.
//------------------------------------------------------------------------------
// This code was generated by Devart Entity Developer tool using Entity Framework EntityObject template.
// Code is generated on: 13.11.2023 13:35:21
//
// Changes to this file may cause incorrect behavior and will be lost if
// the code is regenerated.
//------------------------------------------------------------------------------

using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.Data;
using System.Data.Common;
using System.Data.Entity;
using System.Data.Entity.Core;
using System.Data.Entity.Core.EntityClient;
using System.Data.Entity.Core.Metadata.Edm;
using System.Data.Entity.Core.Objects;
using System.Data.Entity.Core.Objects.DataClasses;
using System.Linq;
using System.Linq.Expressions;
using System.Reflection;
using System.Runtime.Serialization;
using System.Xml.Serialization;

[assembly: EdmSchemaAttribute()]
#region EDM Relationship Metadata

[assembly: EdmRelationshipAttribute("Model", "FK_Konto_User", "Konto", RelationshipMultiplicity.One, typeof(Model.Konto), "Users", RelationshipMultiplicity.Many, typeof(Model.User), true)]

#endregion

namespace Model
{

    /// <summary>
    /// No Metadata Documentation available.
    /// </summary>
    public partial class Entities : ObjectContext
    {
        #region Constructors

        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities() :
                base(@"metadata=res://*/EntityModel.EntityModel.csdl|res://*/EntityModel.EntityModel.ssdl|res://*/EntityModel.EntityModel.msl;provider=MySql.Data.MySqlClient;provider connection string=""persistsecurityinfo=True;server=localhost;user id=root""", "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initializes a new Entities object using the connection string found in the 'Entities' section of the application configuration file.
        /// </summary>
        public Entities(string connectionString) :
                base(connectionString, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }

        /// <summary>
        /// Initialize a new Entities object.
        /// </summary>
        public Entities(EntityConnection connection) : base(connection, "Entities")
        {
            this.ContextOptions.LazyLoadingEnabled = true;
            OnContextCreated();
        }


        #endregion

        #region Partial Methods

        partial void OnContextCreated();

        #endregion

        #region ObjectSet Properties

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aktien> Aktien
        {
            get
            {
                if ((_Aktien == null))
                {
                    _Aktien = base.CreateObjectSet<Aktien>("Aktien");
                }
                return _Aktien;
            }
        }
        private ObjectSet<Aktien> _Aktien;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Aktienwert> Aktienwert
        {
            get
            {
                if ((_Aktienwert == null))
                {
                    _Aktienwert = base.CreateObjectSet<Aktienwert>("Aktienwert");
                }
                return _Aktienwert;
            }
        }
        private ObjectSet<Aktienwert> _Aktienwert;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Apidetails> Apidetails
        {
            get
            {
                if ((_Apidetails == null))
                {
                    _Apidetails = base.CreateObjectSet<Apidetails>("Apidetails");
                }
                return _Apidetails;
            }
        }
        private ObjectSet<Apidetails> _Apidetails;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Finanztransaktionen> Finanztransaktionen
        {
            get
            {
                if ((_Finanztransaktionen == null))
                {
                    _Finanztransaktionen = base.CreateObjectSet<Finanztransaktionen>("Finanztransaktionen");
                }
                return _Finanztransaktionen;
            }
        }
        private ObjectSet<Finanztransaktionen> _Finanztransaktionen;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<Konto> Konto
        {
            get
            {
                if ((_Konto == null))
                {
                    _Konto = base.CreateObjectSet<Konto>("Konto");
                }
                return _Konto;
            }
        }
        private ObjectSet<Konto> _Konto;

        /// <summary>
        /// No Metadata Documentation available.
        /// </summary>
        public ObjectSet<User> User
        {
            get
            {
                if ((_User == null))
                {
                    _User = base.CreateObjectSet<User>("User");
                }
                return _User;
            }
        }
        private ObjectSet<User> _User;

        #endregion
        #region AddTo Methods

        /// <summary>
        /// Deprecated Method for adding a new object to the Aktien EntitySet.
        /// </summary>
        public void AddToAktien(Aktien aktien)
        {
            base.AddObject("Aktien", aktien);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Aktienwert EntitySet.
        /// </summary>
        public void AddToAktienwert(Aktienwert aktienwert)
        {
            base.AddObject("Aktienwert", aktienwert);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Apidetails EntitySet.
        /// </summary>
        public void AddToApidetails(Apidetails apidetails)
        {
            base.AddObject("Apidetails", apidetails);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Finanztransaktionen EntitySet.
        /// </summary>
        public void AddToFinanztransaktionen(Finanztransaktionen finanztransaktionen)
        {
            base.AddObject("Finanztransaktionen", finanztransaktionen);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the Konto EntitySet.
        /// </summary>
        public void AddToKonto(Konto konto)
        {
            base.AddObject("Konto", konto);
        }

        /// <summary>
        /// Deprecated Method for adding a new object to the User EntitySet.
        /// </summary>
        public void AddToUser(User user)
        {
            base.AddObject("User", user);
        }

        #endregion
    }
}
