-- Script was generated by Devart Entity Developer, Version 7.0.0.0
-- Script date 13.11.2023 12:02:35
-- Target Server: MySQL
-- Server Version: 5.5

-- 
-- Creating a table financeapp.Aktien 
-- 
CREATE TABLE financeapp.Aktien (
   ID INT NOT NULL,
   Name VARCHAR(255) NOT NULL,
   PRIMARY KEY (ID)
);

-- 
-- Creating a table financeapp.Aktienwert 
-- 
CREATE TABLE financeapp.Aktienwert (
   ID INT NOT NULL,
   Wert INT NOT NULL,
   `TimeStamp` DATETIME NOT NULL,
   PRIMARY KEY (ID)
);

-- 
-- Creating a table financeapp.Apidetails 
-- 
CREATE TABLE financeapp.Apidetails (
   ID INT NOT NULL,
   PRIMARY KEY (ID)
);

-- 
-- Creating a table financeapp.Finanztransaktionen 
-- 
CREATE TABLE financeapp.Finanztransaktionen (
   ID INT NOT NULL,
   PRIMARY KEY (ID)
);

-- 
-- Creating a table financeapp.Konto 
-- 
CREATE TABLE financeapp.Konto (
   ID INT NOT NULL,
   PRIMARY KEY (ID)
);

-- 
-- Creating a table financeapp.User 
-- 
CREATE TABLE financeapp.User (
   ID INT NOT NULL,
   Vorname VARCHAR(255) NOT NULL,
   Nachname VARCHAR(255) NULL,
   Konto_FK INT NOT NULL,
   PRIMARY KEY (ID),
   CONSTRAINT FK_Konto_User FOREIGN KEY (Konto_FK) REFERENCES financeapp.Konto (ID) ON DELETE NO ACTION
);

